name: mathmechbot

services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    networks:
      - postgres
    restart: always

  postgres:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - pgadmin
      - postgres
    ports:
      - 5432
    restart: unless-stopped
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.12
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    networks:
      - pgadmin
    ports:
      - 5050:80
    restart: always
    secrets:
      - pgadmin_password
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  pgadmin:
    driver: bridge
  postgres:
    driver: bridge

secrets:
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

  pgadmin_password:
    environment: PGADMIN_DEFAULT_PASSWORD

volumes:
  pgadmin:
  pgdata:
